# Gizmo AI - Docker Compose Configuration
# Local development environment setup
#
# Developer: Shashank B
# Repository: https://github.com/ShashankBejjanki1241/GIZMO
# Last Updated: December 2024

version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gizmo_dev
      POSTGRES_USER: gizmo_user
      POSTGRES_PASSWORD: gizmo_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gizmo_dev
      - DB_USER=gizmo_user
      - DB_PASSWORD=gizmo_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8003:8003"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gizmo_dev
      - DB_USER=gizmo_user
      - DB_PASSWORD=gizmo_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENT_MODEL=${AGENT_MODEL:-gpt-4o-mini}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
